### ISSUE TITLE
Board::MoveForce 関数の実装

### ISSUE THREAD

**Issue by grkon03** [tokyotechchess/minichess-AI-1#22]
強制的に Move (1手指す)をする関数
```C++
MCError Board::MoveForce(Square from_square, Square to_square, Piece promotion_piece);
```
キャスリングとアンパッサンとプロモーション以外は(イリーガルでも)
```C++
SetSquare(to_square, GetSquare(from_file, from_rank));
SetSquare(from_square, EMPTYSQ);
```
キャスリング, アンパッサン, プロモーションはそれぞれ実装してください。

キング、ルークが動いた後は castlingPossiblity を false にする
どんなムーブに対しても enpassantAblePawnFile を false にする
その後、ポーンが2マス動いたならば enpassantAblePawnFile を true にする
その後 turn を変更する(turn++ で動きます)

これは重要な関数なのでテストも書いてください
board_test.cpp に書いてください。書き方は他の事例を参照。
例外をできるだけ減らす(量が多いので、起こりうるエラーについて多くやる必要はなく、各事例について1つずつとかで、できるだけ多くの事例を網羅する)

**Comment by grkon03** [comment]
AI を作る際の高速化に使う(LegalMoves みたいな関数で、指せる手を全て取得してくる関数をもとにそれを全探索していくけど、この時に Move を使うと、すでに legal だとわかっているのにまた legal かどうかを判定する羽目になる。これによる低速化を避けるための関数

**Comment by grkon03** [comment]
！！関数の定義変更したので見て！！

**Comment by Ryomatech** [comment]
- [ ] normal move
- [ ] lose castling move
- [ ] pawn double move(make anpas file)
- [ ] take move
- [ ] anpassant take move
- [ ] promotion move

**Comment by Ryomatech** [comment]
これ以外に例が思いつかない

**Comment by grkon03** [comment]
アンパッサンの綴りが違うこと以外は特に気にならんな

**Comment by Ryomatech** [comment]
> アンパッサンの綴りが違うこと以外は特に気にならんな

許して
