### ISSUE TITLE
アルファベータ法の実装

### ISSUE THREAD

**Issue by grkon03** [tokyotechchess/minichess-AI-1#40]
https://github.com/grkon03/blinear/blob/main/src/header/blinear.cpp
↑これの alphabeta() を参考に書く

**Comment by Ryomatech** [comment]
これ一時評価関数の後だよね

**Comment by grkon03** [comment]
そうやね
ただ、適当に 0 を返す関数 tempEvaluator みたいなのを定義しておいて、そこから作れば良い
